### ISSUE TITLE
Bad state: StreamSink is bound to a stream

### ISSUE THREAD

**Issue by FrankTiao** [Jellepepe/flutter_adb#2]
I am encountering a `Bad state: StreamSink is bound to a stream` error when attempting to send a single ADB command using the `flutter_adb` package. The error occurs after the command is sent and seems to be related to the stream handling within the package.

### Code Snippet:
```dart
final crypto = AdbCrypto();
final result = await Adb.sendSingleCommand('getprop', ip: '192.168.0.104', port: 5555, crypto: crypto);
debugPrint('Result: $result');
```

### Error Log:
```
E/flutter ( 6485): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: StreamSink is bound to a stream
E/flutter ( 6485): #0      _StreamSinkImpl._controller (dart:io/io_sink.dart:234:7)
E/flutter ( 6485): #1      _StreamSinkImpl.add (dart:io/io_sink.dart:154:5)
E/flutter ( 6485): #2      _Socket.add (dart:io-patch/socket_patch.dart:2329:38)
E/flutter ( 6485): #3      AdbConnection.sendMessage (package:flutter_adb/adb_connection.dart:105:14)
E/flutter ( 6485): #4      AdbStream.sendReady (package:flutter_adb/adb_stream.dart:41:20)
E/flutter ( 6485): #5      AdbConnection._handleAdbMessage (package:flutter_adb/adb_connection.dart:168:36)
E/flutter ( 6485): #6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter ( 6485): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
E/flutter ( 6485): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
E/flutter ( 6485): #9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 6485): #10     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter ( 6485): #11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 6485): #12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter ( 6485): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
E/flutter ( 6485): #14     _DelayedData.perform (dart:async/stream_impl.dart:541:14)
E/flutter ( 6485): #15     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
E/flutter ( 6485): #16     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
E/flutter ( 6485): #17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 6485): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 6485): 
I/flutter ( 6485): Timeout closing the stream.
I/flutter ( 6485): Result: 
```

### Environment:
- **Flutter Version:** Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
- **Android Toolchain:** Android SDK version 35.0.0
- **Package Version:** `flutter_adb: ^0.1.1`
- **Test Device:** Android 14

---

Please let me know if you need any further information or if there are any additional steps I can take to help resolve this issue.

---

**Comment by Jellepepe** [comment]
Hello @FrankTiao , Thanks for the report.

From a quick browse on my phone it seems to indeed be a race condition in the internal handling of the socket underlying the adb protocol.
It occurs when the protocol attempts to send a 'ready' command after processing a write message (from the client) before the previous message is flushed. Most likely this only occurs with commands that give a large return value and/or on slower networks, which is why I did not notice it during testing.

I will likely be able to push the fix to a release tomorrow, as soon as I get on my PC.

**Comment by FrankTiao** [comment]
Thanks for looking into this! 
I updated to the latest Git commit, but the issue is still there. Any additional steps or info you need from me?

**Comment by Jellepepe** [comment]
Oh. That is bizarre, I was able to replicate the issue a few times with the old version but this commit resolved that condition. I only had very limited time to look at it though, so I will see if I can replicate it again.

I assume the error is the exact same and you confirmed the new code is indeed pulled?
Ill perform additional tests once I have time over the following days.

**Comment by FrankTiao** [comment]
> Oh. That is bizarre, I was able to replicate the issue a few times with the old version but this commit resolved that condition. I only had very limited time to look at it though, so I will see if I can replicate it again.
> 
> I assume the error is the exact same and you confirmed the new code is indeed pulled? Ill perform additional tests once I have time over the following days.

Thanks, Jellepepe! I appreciate you looking into this. I've definitely updated to the latest commit and the issue persists. The error is exactly the same, and I've confirmed I'm running the latest code. Let me know if there's anything else I can do to help.

**Comment by Jellepepe** [comment]
I totally forgot about this but this should now be fixed as of 0a1cb049848166664836ca03cf4501d02f20bcd4 
Please let me know if it still appears on the latest version, for me it does not.
